/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

/**
 *
 * @author marga
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        Correo = new javax.swing.JTextField();
        MantenerConectado = new javax.swing.JRadioButton();
        Entrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        contrasena1 = new javax.swing.JPasswordField();
        Correo1 = new javax.swing.JTextField();
        Entrar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        contrasena2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(750, 526));

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Iniciar Sesión");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 20, 190, 60);

        contrasena.setForeground(new java.awt.Color(102, 102, 102));
        contrasena.setText("jPasswordField1");
        contrasena.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        contrasena.setOpaque(false);
        contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(contrasena);
        contrasena.setBounds(400, 250, 220, 40);

        Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Correo.setForeground(new java.awt.Color(102, 102, 102));
        Correo.setText("example@epn.edu.ec");
        Correo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        Correo.setOpaque(false);
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        jPanel1.add(Correo);
        Correo.setBounds(400, 170, 220, 40);

        MantenerConectado.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        MantenerConectado.setForeground(new java.awt.Color(51, 51, 51));
        MantenerConectado.setText("Mantener Conectado");
        MantenerConectado.setOpaque(false);
        jPanel1.add(MantenerConectado);
        MantenerConectado.setBounds(390, 310, 190, 25);

        Entrar.setBackground(new java.awt.Color(51, 51, 51));
        Entrar.setForeground(new java.awt.Color(51, 51, 51));
        Entrar.setText("Entrar");
        jPanel1.add(Entrar);
        Entrar.setBounds(400, 350, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("EMAIL");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 150, 100, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Registarse");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 400, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("CONTRASEÑA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 230, 110, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WhatsApp Image 2021-09-12 at 14.39.42.jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 526);

        jPanelSlider1.add(jPanel1, "card2");

        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Ebrima", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Registrarse");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 20, 190, 60);

        contrasena1.setForeground(new java.awt.Color(102, 102, 102));
        contrasena1.setText("jPasswordField1");
        contrasena1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        contrasena1.setOpaque(false);
        contrasena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasena1ActionPerformed(evt);
            }
        });
        jPanel2.add(contrasena1);
        contrasena1.setBounds(120, 220, 220, 40);

        Correo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Correo1.setForeground(new java.awt.Color(102, 102, 102));
        Correo1.setText("example@epn.edu.ec");
        Correo1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        Correo1.setOpaque(false);
        Correo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Correo1ActionPerformed(evt);
            }
        });
        jPanel2.add(Correo1);
        Correo1.setBounds(120, 140, 220, 40);

        Entrar1.setBackground(new java.awt.Color(51, 51, 51));
        Entrar1.setForeground(new java.awt.Color(51, 51, 51));
        Entrar1.setText("Registrar");
        jPanel2.add(Entrar1);
        Entrar1.setBounds(120, 370, 220, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("EMAIL");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 130, 100, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Entrar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(540, 250, 70, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("CONFIRMAR CONTRASEÑA");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(120, 280, 210, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("CONTRASEÑA");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(120, 200, 110, 17);

        contrasena2.setForeground(new java.awt.Color(102, 102, 102));
        contrasena2.setText("jPasswordField1");
        contrasena2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        contrasena2.setOpaque(false);
        contrasena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasena2ActionPerformed(evt);
            }
        });
        jPanel2.add(contrasena2);
        contrasena2.setBounds(120, 310, 220, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reptar.jpeg"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 0, 750, 526);

        jPanelSlider1.add(jPanel2, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
        Correo.setText("");
    }//GEN-LAST:event_CorreoActionPerformed

    private void contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaActionPerformed
        // TODO add your handling code here:
        contrasena.setText("");
    }//GEN-LAST:event_contrasenaActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here
        jPanelSlider1.nextPanel(5, jPanel2, jPanelSlider1.left);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void contrasena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasena1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasena1ActionPerformed

    private void Correo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Correo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Correo1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(5, jPanel1, jPanelSlider1.right);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void contrasena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasena2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasena2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Correo1;
    private javax.swing.JButton Entrar;
    private javax.swing.JButton Entrar1;
    private javax.swing.JRadioButton MantenerConectado;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JPasswordField contrasena1;
    private javax.swing.JPasswordField contrasena2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    // End of variables declaration//GEN-END:variables
}
